### PR TITLE
Remove extra single quotes in _kaiti.scss

### PR DESCRIPTION
**Pull request by kanru**

### CODE REVIEW

**Comment by ethantw** [comment]
thanks!

**Comment by ethantw** [comment]
@kanru:

Does this cause real-time bug in browsers of any kind? If so, I'll have to release this patch right away. Or could this wait until the next release? Thanks.

**Comment by kanru** [comment]
@ethantw 

I'm not sure the impact of this. It depends on the usage of the two fonts: 'Han Kaiti' and 'Han Kaiti CNS'. The original code generates incorrect css that leads to parsing error so only the first local font variant 'Kaiti TC Bold' will be used.

**Comment by ethantw** [comment]
Thanks for your immediate reply. 👍  I think this can wait for the next release.

**Pull request merged**
